#!/usr/bin/env bash

echo "Creating VPC..."

if ! command -v aws &> /dev/null
then
    echo "aws cli command is required"
    exit 1
fi

while [[ -z "$VPC_NAME" || -z "$CIDR_BLOCK" ]]; do
    read -rp "Please enter your VPC name and CIDR block: " VPC_NAME CIDR_BLOCK
done

# if [ -z "$CIDR_BLOCK" ]; then
#     echo "No CIDR Block provided!"
#     exit 1
# fi

# set region
AWS_DEFAULT_REGION="us-east-1"
# Create VPC with CIDR block
VPC_ID=$(aws ec2 create-vpc --cidr-block "$CIDR_BLOCK" --tag-specifications "ResourceType=vpc,Tags=[{Key=Name,Value="$VPC_NAME"}]" \
--region "$AWS_DEFAULT_REGION" --query Vpc.VpcId --output text 2>&1)

STATUS=$?
if [ $STATUS -eq 0 ]; then
    echo "VPC $VPC_NAME with CIDR block $CIDR_BLOCK created successfully: $VPC_ID"
    
    echo "===============================\nAuto assign IPv4 addresses..."
    # Enable the IPv4 address auto assign
    IPV4_AUTO=$(aws ec2 modify-vpc-attribute --vpc-id $VPC_ID --enable-dns-hostnames "{\"Value\":true}")

    echo "===================================\nCreating subnet for this VPC..."
    # Create a subnet for the VPC
    SUBNET_OUTPUT=$(aws ec2 create-subnet --vpc-id "$VPC_ID" --cidr-block "$CIDR_BLOCK" --query Subnet.SubnetId --output text 2>&1)
    STATUS_2=$?
    if [ $STATUS_2 -eq 0 ]; then
        echo "Subnet created successfully, Subnet Id:$SUBNET_OUTPUT"

        echo "===============================\nAuto assign IPv4 addresses..."
        # Enable the IPv4 address auto assign
        IPV4_AUTO=$(aws ec2 modify-subnet-attribute --subnet-id $SUBNET_OUTPUT --map-public-ip-on-launch)

        echo "===============================\nAttaching the default route table to the subnet..."
        # Retrive the default route table ID
        RT_ID=$(aws ec2 describe-route-tables --filters "Name=vpc-id,Values=$VPC_ID" "Name=association.main, Values=true" --query "RouteTables[].RouteTableId[]" --output text 2>&1)
        if [$RT_ID != "None"]; then
            # Associate the default RT ID to the Subnet
            RT_OUTPUT=$(aws ec2 associate-route-table --route-table-id $RT_ID --subnet-id $SUBNET_OUTPUT 2>&1)
            STATUS_2=$?
            if [ $STATUS_2 -eq 0 ]; then
                echo "Default route table attached successfully, "

                echo "=======================\nAdding a route to a route table..."
                # Attach some routes to the route table
                ROUTES_OUTPUT=$(aws ec2 create-route --route-table-id $RT_ID --destination-cidr-block $CIDR_BLOCK)
            else
                echo "Error creating VPC subnet: $SUBNET_OUTPUT"
                exit 1
            fi
        fi
    else
        echo "Error creating VPC subnet: $SUBNET_OUTPUT"
        exit 1
    fi
else
    echo "Error creating VPC $VPC_NAME: $VPC_ID"
    exit 1
fi