#!/usr/bin/env bash

echo "Creating an IGW..."

if ! command -v aws &> /dev/null
then
    echo "aws cli command is required"
    exit 1
fi

# Create IGW
CREATE_OUTPUT=$(aws ec2 create-internet-gateway \
--query InternetGateway.InternetGatewayId \
--output text 2>&1)
STATUS=$?
if [ $STATUS -eq 0 ]; then
    # Attach IGW to a VPC ID
    $VPC_ID=$1
    echo "Attaching the IGW $CREATE_OUTPUT to the VPC $1..."
    ATTACH_OUTPUT=$(aws ec2 attach-internet-gateway \
--internet-gateway-id $CREATE_OUTPUT \
--vpc-id $VPC_ID \
--output text 2>&1)

    STATUS_2=$?
    if [ $STATUS_2 -eq 0 ]; then
        echo "$ATTACH_OUTPUT"
        exit 0
    else
        echo "Error attaching IGW to VPC: $ATTACH_OUTPUT"
        exit 1
    fi

else
    echo "Error retrieving VPCs: $OUTPUT"
    exit 1
fi

