#!/usr/bin/env bash

echo "Deleting VPC and attached components..."

if ! command -v aws &> /dev/null
then
    echo "aws cli command is required"
    exit 1
fi
# List the available VPCs
./vpc-basics/list-vpc

while [[ -z "$VPC_ID" ]]; do
    read -rp "Please enter your VPC ID: " VPC_ID
done

echo -e "===================================\nDetaching and Deleting attached Internet Gateways..."
# Detach the IGW and delete if present
for igw in $(aws ec2 describe-internet-gateways \
--filters "Name=attachment.vpc-id,Values=$VPC_ID" \
--query "InternetGateways[].InternetGatewayId" \
--output text); do
    aws ec2 detach-internet-gateway --internet-gateway-id "$igw" --vpc-id "$VPC_ID" --output text 2>&1
    aws ec2 delete-internet-gateway --internet-gateway-id "$igw" --output text 2>&1
done

echo -e "===================================\nDeleting the route table associations..."
# Delete the route table association
for rta in $(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" \
--query "RouteTables[].Associations[].RouteTableAssociationId" \
--output text); do
    aws ec2 disassociate-route-table --association-id "$rta" --output text 2>&1
done

echo -e "===================================\nDeleting attached subnets..."
# Delete the subnet
for subnet in $(aws ec2 describe-subnets \
--filters "Name=vpc-id,Values=$VPC_ID" \
--query "Subnets[].SubnetId" \
--output text); do
    aws ec2 delete-subnet --subnet-id "$subnet" --output text 2>&1
done

echo -e "===================================\nDeleting attached route tables..."

# Delete the route table
for rt in $(aws ec2 describe-route-tables \
--filters "Name=vpc-id,Values=$VPC_ID" \
--query "RouteTables[].RouteTableId" \
--output text); do
    aws ec2 delete-route-table --route-table-id "$rt" --output text 2>&1
done



echo -e "===================================\nDeleting the security groups..."
# delete any security groups attached
for sg in $(aws ec2 describe-security-groups \
--filters "Name=vpc-id,Values=$VPC_ID" \
--query "SecurityGroups[].GroupId" \
--output text); do
    aws ec2 delete-security-group --group-id "$sg" --output text 2>&1
done

echo -e "===================================\nDeleting the VPC..."
# Delete the VPC
OUTPUT=$(aws ec2 delete-vpc --vpc-id $VPC_ID --output text 2>&1)

STATUS=$?
if [ $STATUS -eq 0 ]; then
    echo "VPC $VPC_ID  deleted successfully: $OUTPUT"
    exit 0
else
    echo "Error deleting VPC $VPC_ID: $OUTPUT"
    exit 1
fi