#!/usr/bin/env bash
echo "Listing VPCs..."

if ! command -v aws &> /dev/null
then
    echo "aws cli command is required"
    exit 1
fi

OUTPUT=$(aws ec2 describe-vpcs --region us-east-1 \
--query "Vpcs[*].{ID:VpcId,Name:Tags[?Key=='Name']|[0].Value,CIDR:CidrBlock,State:State}" \
--output table 2>&1)
STATUS=$?
if [ $STATUS -eq 0 ]; then
    echo "$OUTPUT"
    exit 0
else
    echo "Error retrieving VPCs: $OUTPUT"
    exit 1
fi