#!/usr/bin/env bash
echo "Listing the objects in a bucket..."

# check for the aws command
if ! command -v aws &> /dev/null;  then
    echo "aws cli not found"
    exit 1
fi

# Check for the bucket variable
BUCKET_NAME=$1
if [ -z "$BUCKET_NAME" ]; then
    echo "Bucket name not provided!"
    exit 1
fi

# list the objects in the bucket
OUTPUT=$(aws s3api list-objects --bucket "$BUCKET_NAME" --query 'Contents[].Key' 2>&1)
STATUS=$?

if [ $STATUS -eq 0 ]; then
    echo "$OUTPUT"
    exit 0
elif echo "$OUTPUT" | grep -q "AccessDenied"; then
    echo "Access Denied: $OUTPUT"
    exit 1
elif echo "$OUTPUT" | grep -q "NoSuchBucket"; then
    echo "Bucket does not exist: $OUTPUT"
    exit 1
else
    echo "Error retrieving object: $OUTPUT"
    exit 1
fi